Klarstellung, dass das Verschieben eines Termins nur durchgeführt werden soll, wenn der vorgeschlagene Termin verfügbar ist
gematik/ISiK-Terminplanung pull request #170
Opened 2024-02-25 20:24 UTC by alexzautke

Partial fix for #169

2024-03-07 08:24 UTC, f-peverali requested changes

2024-03-07 08:24 UTC, f-peverali commented on Resources/input/fsh/ISiKBookOperation.fsh
> +  * documentation	= "Für die vorliegende Spezifikation ist die Verschiebung eines Termin eins zwei-stufiger Prozess, bei dem ein Termin storniert und ein neuer Termin neu gebucht wird. Dieser Paramet
question: Aus welchem Kontext / Ticket kommt diese Änderung ?

suggestion: "atomar" würde ich anders verstehen, nämlich dass eine Operation selbst nicht aus weiteren Sub-Operationen besteht - was hier aber nicht der Fall ist, da Verschieben bisher zusammengesetzt ist aus Löschen und Neubuchung als Operationen. Ich würde eher von "transaktional" sprechen - also : ganz oder gar nicht , grob.

2024-03-07 08:40 UTC, alexzautke commented
@f-peverali Hab den Satz angepasst. Danke! Den PR hatte ich als Klarstellung zu #169 verfasst.

2024-03-12 10:30 UTC, f-peverali approved these changes

2024-03-12 10:30 UTC, merged