Feature/update kommunikation UCs pt data 886
gematik/ISiK-Terminplanung pull request #173
Opened 2024-03-12 14:25 UTC by f-peverali

## Pull Request Short Cut
Großteil der Aspekte von PTDATA-886

2024-03-12 15:08 UTC, alexzautke approved these changes

2024-03-12 15:13 UTC, AnsgarHoeper requested changes

2024-03-12 15:13 UTC, AnsgarHoeper commented on ImplementationGuide/markdown/Zusammenfassung/UseCases.md
> +  * Übergreifende Use Cases und und ihre Sub Use Cases können in einem separaten Diagram auf den entsprechenden Seiten gefunden werden.
*Diagram**m**

2024-03-12 15:13 UTC, AnsgarHoeper commented on ImplementationGuide/markdown/Zusammenfassung/UseCases.md
> +* In den Funktionen werde triviale Suchen einer Ressource anhand ihrer eigenen Properties nicht dargestellt, z.B. Suche einer Ressource anhand der ID, Name, Code usw.
*werde**n**

2024-03-12 15:13 UTC, AnsgarHoeper commented on ImplementationGuide/markdown/Zusammenfassung/UseCases.md
> +Der Use Case rund um die Benachrichtigung, in Folge "Kommunikation", lässt sich ausdifferenzieren in folgende, die nicht alle durch ISiK sinnvollerweise abgedeckt werden kann, sondern wofür ggf. ande
Satz schwer verständlich. Sofern inhaltlich korrekt hier ein Alternativvorschlag:

Der Use Case rund um die Benachrichtigung, im Folgenden "Kommunikation" genannt, lässt sich in folgende Szenarien ausdifferenzieren. Sofern ISiK an bestimmten Stellen nicht geeignet erscheint wird nachfolgend eine Alternative vorgeschlagen:

2024-03-12 15:13 UTC, AnsgarHoeper commented on ImplementationGuide/markdown/Zusammenfassung/UseCases.md
> +    - Absprache des Termins: "Anfrage des Leistungserbringers: Gibt es an diesem Datum noch einen freien Termin?" -> TIM (?)
TIM ist ein geschützter Begriff. Bitte wie folgt ausschreiben: TI-Messenger

2024-03-12 15:13 UTC, AnsgarHoeper commented on ImplementationGuide/markdown/Zusammenfassung/UseCases.md
> +    - Rückfragen: Rückfrage des Leistungserbringers zur Terminanfrage -> TIM (?)
TIM ist ein geschützter Begriff. Bitte wie folgt ausschreiben: TI-Messenger

2024-03-13 08:23 UTC, f-peverali commented on ImplementationGuide/markdown/Zusammenfassung/UseCases.md
> +  * Übergreifende Use Cases und und ihre Sub Use Cases können in einem separaten Diagram auf den entsprechenden Seiten gefunden werden.
```suggestion
  * Übergreifende Use Cases und und ihre Sub Use Cases können in einem separaten Diagramm auf den entsprechenden Seiten gefunden werden.
```

2024-03-13 08:23 UTC, f-peverali commented on ImplementationGuide/markdown/Zusammenfassung/UseCases.md
> +* In den Funktionen werde triviale Suchen einer Ressource anhand ihrer eigenen Properties nicht dargestellt, z.B. Suche einer Ressource anhand der ID, Name, Code usw.
```suggestion
* In den Funktionen werden triviale Suchen einer Ressource anhand ihrer eigenen Properties nicht dargestellt, z.B. Suche einer Ressource anhand der ID, Name, Code usw.
```

2024-03-13 08:24 UTC, f-peverali commented on ImplementationGuide/markdown/Zusammenfassung/UseCases.md
> +Der Use Case rund um die Benachrichtigung, in Folge "Kommunikation", lässt sich ausdifferenzieren in folgende, die nicht alle durch ISiK sinnvollerweise abgedeckt werden kann, sondern wofür ggf. ande
```suggestion
Der Use Case rund um die Benachrichtigung, im Folgenden "Kommunikation" genannt, lässt sich in folgende Szenarien ausdifferenzieren. Sofern ISiK an bestimmten Stellen nicht geeignet erscheint wird nachfolgend eine Alternative vorgeschlagen:
```

2024-03-13 08:24 UTC, f-peverali commented on ImplementationGuide/markdown/Zusammenfassung/UseCases.md
> +    - Absprache des Termins: "Anfrage des Leistungserbringers: Gibt es an diesem Datum noch einen freien Termin?" -> TIM (?)
```suggestion
    - Absprache des Termins: "Anfrage des Leistungserbringers: Gibt es an diesem Datum noch einen freien Termin?" -> TI-Messenger (?)
```

2024-03-13 08:25 UTC, f-peverali commented on ImplementationGuide/markdown/Zusammenfassung/UseCases.md
> +    - Rückfragen: Rückfrage des Leistungserbringers zur Terminanfrage -> TIM (?)
```suggestion
    - Rückfragen: Rückfrage des Leistungserbringers zur Terminanfrage -> TI-Messenger (?)
```

2024-03-13 08:27 UTC, merged