Fix/binary requirement ptdata 955
gematik/ISiK-Terminplanung pull request #181
Opened 2024-03-27 14:53 UTC by f-peverali

## Pull Request Short Cut
Solves PTDATA 955

## Reviewer (minimal) Checklist
- [ ] alle Anforderungs-Attribute (MUSS/KANN/SOLL) geprüft
- [ ] Testing-Anpassungen intern abgestimmt

2024-03-27 15:07 UTC, alexzautke requested changes
Vorschlag zum diskutieren...

2024-03-27 15:07 UTC, alexzautke commented on ImplementationGuide/markdown/Datenobjekte/ISiKBinary.md
> +Da die ISiKNachricht NICHT unterstützt werden MUSS, gilt für die ISiKBinary: diese SOLL unterstützt werden, falls eine ISiKNachricht unterstützt wird.
```suggestion
Da die ISiKNachricht NICHT unterstützt werden MUSS, gilt für die ISiKBinary: diese MUSS unterstützt werden, falls eine ISiKNachricht unterstützt wird.
```
```suggestion
Da die ISiKNachricht NICHT unterstützt werden MUSS, gilt für die ISiKBinary: diese SOLL unterstützt werden, falls eine ISiKNachricht unterstützt wird.
```

2024-03-27 15:14 UTC, f-peverali commented on ImplementationGuide/markdown/Datenobjekte/ISiKBinary.md
> +Da die ISiKNachricht NICHT unterstützt werden MUSS, gilt für die ISiKBinary: diese SOLL unterstützt werden, falls eine ISiKNachricht unterstützt wird.
SOLL oder MUSS ist hier nicht sonderlich kritisch... entscheiden ist die Form des Testing, denke ich. FYI @alexey-tschudnowsky

2024-03-27 15:15 UTC, f-peverali commented on ImplementationGuide/markdown/Datenobjekte/ISiKBinary.md
> +Da die ISiKNachricht NICHT unterstützt werden MUSS, gilt für die ISiKBinary: diese SOLL unterstützt werden, falls eine ISiKNachricht unterstützt wird.
Da wir die Diskussion schon hatten, @alexey-tschudnowsky DU auch hier eher für "MUSS"?

2024-03-28 08:45 UTC, alexey-tschudnowsky commented on ImplementationGuide/markdown/Datenobjekte/ISiKBinary.md
> +Da die ISiKNachricht NICHT unterstützt werden MUSS, gilt für die ISiKBinary: diese SOLL unterstützt werden, falls eine ISiKNachricht unterstützt wird.
ich bin auch für MUSS (falls ISIKNachricht implementiert wird)

2024-03-28 08:45 UTC, f-peverali commented on Resources/input/fsh/ISiKTerminplanungCapabilityStatement.fsh
> +    * extension.valueCode = #MAY
suggestion: ggf. SHALL - siehe Diskussion zur ISiKBinary als Ganzer

2024-03-28 08:45 UTC, f-peverali commented on Resources/input/fsh/ISiKTerminplanungCapabilityStatement.fsh
> +    * extension.valueCode = #MAY
s.o.

2024-03-28 09:05 UTC, f-peverali commented on Resources/input/fsh/ISiKTerminplanungCapabilityStatement.fsh
> +  * extension.valueCode = #MAY
```suggestion
  * extension.valueCode = #SHALL
```

2024-03-28 09:05 UTC, f-peverali commented on Resources/input/fsh/ISiKTerminplanungCapabilityStatement.fsh
> +    * extension.valueCode = #MAY
```suggestion
    * extension.valueCode = #SHALL
```

2024-03-28 09:06 UTC, f-peverali commented on Resources/input/fsh/ISiKTerminplanungCapabilityStatement.fsh
> +    * extension.valueCode = #MAY
```suggestion
    * extension.valueCode = #SHALL
```

2024-04-02 12:11 UTC, f-peverali commented on ImplementationGuide/markdown/Datenobjekte/ISiKBinary.md
> +Da die ISiKNachricht NICHT unterstützt werden MUSS, gilt für die ISiKBinary: diese MUSS unterstützt werden, falls eine ISiKNachricht unterstützt wir. Iin diesem Sinne sind auch die Vorgaben 'SHALL' i
```suggestion
Da die ISiKNachricht NICHT unterstützt werden MUSS, gilt für die ISiKBinary: diese MUSS unterstützt werden, falls eine ISiKNachricht unterstützt wir. In diesem Sinne sind auch die Vorgaben 'SHALL' im CapabilityStatement als bedingte zu verstehen.
```

2024-05-07 14:00 UTC, merged