Feature/ptdata 1053 tc stufe 3 zu stufe 4
gematik/ISiK-Terminplanung pull request #187
Opened 2024-06-19 11:43 UTC by f-peverali

# Contributor Pull Request

## Description
Integrate TC Stufe 3 Changes into Stufe 4

2024-06-23 21:27 UTC, alexzautke requested changes

2024-06-23 21:27 UTC, alexzautke commented on ImplementationGuide/markdown/Datenobjekte/ISiKBinary.md
> +Da die ISiKNachricht NICHT unterstützt werden MUSS, gilt für die ISiKBinary: diese MUSS unterstützt werden, falls eine ISiKNachricht unterstützt wir. In diesem Sinne sind auch die Vorgaben 'SHALL' im
Dieses SHALL gibt es nicht mehr

2024-06-24 08:58 UTC, jschoen-gefyra commented on ImplementationGuide/markdown/Datenobjekte/ISiKBinary.md
> +Da die ISiKNachricht NICHT unterstützt werden MUSS, gilt für die ISiKBinary: diese MUSS unterstützt werden, falls eine ISiKNachricht unterstützt wir. In diesem Sinne sind auch die Vorgaben 'SHALL' im
Habe den zweiten Teil des Satzes entfernt.

2024-06-24 09:00 UTC, jschoen-gefyra commented
@f-peverali ich kann dich leider nicht als Reviewer setzen, da du den geöffnet hast. Bitte schau mal drüber, hab die WIldcard noch ergänzt und Alex Kommentar gelöst. Ist glaube ich alles für das Modul jetzt.

2024-06-25 07:36 UTC, f-peverali reviewed
question: ich habe den Verdacht, dass der Status als Preleases (4.0.0-rc2) die Probleme beim auflösen in der Registry verursacht. @alexzautke oder @patrick-werner habt ihr hier Erfahrungen oder eine Meinung?

suggestion: mein Vorschlag wäre hier auf das update der Dependency wildcard zunächst zu verzichten und es im Nachhinein zu tun.

2024-06-25 07:38 UTC, f-peverali commented on Resources/sushi-config.yaml
> +  de.gematik.isik-basismodul: 4.0.x
```suggestion
  de.gematik.isik-basismodul: 4.0.0-rc2

```

2024-06-25 07:38 UTC, f-peverali commented on package.json
> +        "de.gematik.isik-basismodul": "4.0.x",
```suggestion
        "de.gematik.isik-basismodul": "4.0.0-rc2",

```

2024-06-25 07:42 UTC, alexzautke commented
Ich hab gestern schon beim Simplifier Support nachgefragt aber noch keine Antwort bekommen. Würde es auch erstmal rausnehmen.

2024-06-25 07:46 UTC, f-peverali commented
@alexzautke , leider bricht die Pipeline trotzdem. Die DOTNET Validierung (aus firrelyterminal) kann neuerdings nciht mit der Angabe der FHIR-Version (die schon immer da) umgehen?! Klingt merkwürdig. 
... Kannst du  das einordnen?

2024-06-25 07:51 UTC, alexzautke commented
Jetzt sieht's gut aus!

2024-06-25 07:52 UTC, f-peverali commented
gelöst: offensichltich war es ein Syntax-Fehler (blank line) in der sushi-config

2024-06-25 07:52 UTC, f-peverali commented on package.json
> +
```suggestion
```

2024-06-25 07:54 UTC, f-peverali commented on ImplementationGuide/markdown/Datenobjekte/ISiKBinary.md
> +Da die ISiKNachricht NICHT unterstützt werden MUSS, gilt für die ISiKBinary: diese MUSS unterstützt werden, falls eine ISiKNachricht unterstützt wir.
```suggestion
Da die ISiKNachricht NICHT unterstützt werden MUSS, gilt für die ISiKBinary: diese MUSS unterstützt werden, falls eine ISiKNachricht unterstützt wird.
```

2024-06-25 07:56 UTC, f-peverali commented on ImplementationGuide/markdown/Datenobjekte/ISiKNachrichtCommunication.md
> +**Hinweis:** Ein bestätigungsrelevantes System MUSS sowohl Freitext, als auch base64-kodierte Inhalte unterstützten. Falls strukturierte Metadaten über das zu übermittelnde Dokument verfügbar sind, K
```suggestion
**Hinweis:** Ein bestätigungsrelevantes System MUSS sowohl Freitext, als auch base64-kodierte Inhalte unterstützten. Falls strukturierte Metadaten über das zu übermittelnde Dokument verfügbar sind, KANN ein bestätigungsrelevantes System es als DocumentReference-Ressource ablegen. Für die Anlage einer solchen Ressource wird auf das [ISiK Dokumentenaustausch](https://simplifier.net/guide/isik-dokumentenaustausch-v4?version=current) verwiesen. Die erzeugte Ressource SOLL anschließend durch das bestätigungsrelevante System unter dem contentReference-Element als Referenz angegeben werden. Jegliche Funktionalität bezogen auf das Modul Dokumentenaustausch ist nicht bestätigungsrelevant. Dokumente welche als Attachment angegeben werden, MÜSSEN in ihrer URL auf eine [ISiKBinary](https://simplifier.net/guide/isik-basis-v4/ImplementationGuide-markdown-Datenobjekte-Datenobjekte_Binary?version=current) Ressource verweisen. Diese Binary-Ressource SOLL per CREATE-Interaktion angelegt werden im empfangenden System.
```

2024-06-25 07:58 UTC, merged