Allow multiple codings for “Fachrichtung” and “ErweiterterFachabteilungsschluessel” slices on .specialty
gematik/ISiK-Terminplanung pull request #204
Opened 2024-07-10 09:22 UTC by alexzautke

Fixes PTDATA-1103

2024-07-10 09:43 UTC, f-peverali commented on Resources/input/fsh/ISiKTermin.fsh
> +* specialty.coding[ErweiterterFachabteilungsschluessel] from $FachabteilungsschluesselErweitertVS (required)
praise: das war ein offensichtlicher Error, der gefixed werden muss.
suggestion: ggf. kann der fix auch vorab geschehen.

2024-07-10 10:39 UTC, f-peverali commented on Resources/input/fsh/ISiKMedizinischeBehandlungseinheit.fsh
>    Fachrichtung 1..1 MS and
question/issue: Wirklich nur 1 Fachrichtung Codierbar für das Profil Behandlungseinheit?
todo: hier in jedem Fal Motivation für Kardinalität hinzu (mit Verweis auch das "Design" von ISIKMedizinischeBehandlungseinheit

2024-07-10 11:24 UTC, f-peverali commented on Resources/input/fsh/ISiKTermin.fsh
> +  * ^comment = "Optionale Angabe aller Fachbereiche aus denen ein oder mehere Akteuere die für die Durchführung des Termins benötigt werden. KANN auch anhand des Kalenders in dem ein Termin gebucht w
```suggestion
  * ^comment = "Optionale Angabe aller Fachbereiche aus denen ein oder mehere Akteuere die für die Durchführung des Termins benötigt werden. KANN auch anhand des Kalenders, in dem ein Termin gebucht wird, ermittelt werden."
```

2024-07-10 11:25 UTC, f-peverali commented on Resources/fsh-generated/resources/StructureDefinition-ISiKTermin.json
> +        "comment": "Optionale Angabe aller Fachbereiche aus denen ein oder mehere Akteuere die für die Durchführung des Termins benötigt werden. KANN auch anhand des Kalenders in dem ein Termin gebuc
```suggestion
        "comment": "Optionale Angabe aller Fachbereiche aus denen ein oder mehere Akteuere die für die Durchführung des Termins benötigt werden. KANN auch anhand des Kalenders, in dem ein Termin gebucht wird, ermittelt werden.",
```

2024-07-10 11:27 UTC, f-peverali approved these changes
todo: typos

suggestion: ggf. noch im Comment darauf hinweisen, dass die Behandlungseinheit ggf. multiprofessionell sein kann und daher auch verschiedene Fachbereiche abdecken können muss.

praise: fachlich passt es mMn

2024-07-10 13:41 UTC, f-peverali commented on Resources/input/fsh/ISiKTermin.fsh
> +  * ^comment = "Optionale Angabe aller Fachbereiche aus denen ein oder mehere Akteuere die für die Durchführung des Termins benötigt werden. KANN auch anhand des Kalenders, in dem ein Termin gebucht
```suggestion
  * ^comment = "Optionale Angabe aller Fachbereiche aus denen ein oder mehrere Akteure für die Durchführung des Termins benötigt werden. KANN auch anhand des Kalenders, in dem ein Termin gebucht wird, ermittelt werden."
```

2024-07-10 13:42 UTC, f-peverali commented on Resources/input/fsh/ISiKMedizinischeBehandlungseinheit.fsh
> +  * ^comment = "Kodierung alle Fachbereiche unter die die Behandlungseinheit fällt."
```suggestion
  * ^comment = "Kodierung aller Fachbereiche unter die die Behandlungseinheit fällt."
```

2024-07-10 13:45 UTC, f-peverali commented on Resources/input/fsh/ISiKKalender.fsh
> +  * ^comment = "Ein Kalendar kann für einen Akteur gepflegt werden. Dieser Akteur kann in einer oder mehreren Fachrichtungen agieren. Für die Ressourcenplannung (z.B. welche Akteure sind für einen Te
question: wirklich "Speciality"? Im Fall eines Practitioners heißt es "qualification".

2024-07-10 13:46 UTC, f-peverali commented on Resources/input/fsh/ISiKKalender.fsh
> +  * ^comment = "Ein Kalendar kann für einen Akteur gepflegt werden. Dieser Akteur kann in einer oder mehreren Fachrichtungen agieren. Für die Ressourcenplannung (z.B. welche Akteure sind für einen Te
```suggestion
  * ^comment = "Ein Kalender kann für einen Akteur gepflegt werden. Dieser Akteur kann in einer oder mehreren Fachrichtungen agieren. Für die Ressourcenplanung (z.B. welche Akteure sind für einen Termin verfügbar) sollte auch auf die Speciality des Akteurs zurückgegriffen werden für den Fall, dass ein Kalender pro Fachbereich gepflegt wird."
```

2024-07-10 13:50 UTC, f-peverali requested changes
siehe andere Kommentare

2024-08-09 11:41 UTC, patrick-werner approved these changes

2024-08-09 11:53 UTC, merged