add documentation for cardinality and MS
gematik/ISiK-Terminplanung pull request #209
Opened 2024-09-27 13:22 UTC by f-peverali

# Contributor Pull Request

## Description
add documentation for cardinality and MS as a comment

## Motivation and Context
solves PTDATA-1107

## How has this been tested?

## Snippets or Screenshots (if necessary):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this IG / specification.
- [ ] My change requires a change to the documentation or narrative (intend) of the IG.
- [ ] I have already updated the documentation / narrative (intend) accordingly.

2024-10-01 11:16 UTC, patrick-werner commented
Es wird manchmal beschrieben:
`Begründung Kardinalität und Must Support` und manchmal nur `Begründung Kardinalität` (obwohl auch MS gesetzt).
Vorschlag:
nur MS: Begründung Must Support
nur Kard: Begründung Kardinalität
beides: Begründung Kardinalität und Must Support

2024-10-01 13:26 UTC, f-peverali commented
> Es wird manchmal beschrieben: `Begründung Kardinalität und Must Support` und manchmal nur `Begründung Kardinalität` (obwohl auch MS gesetzt). Vorschlag: nur MS: Begründung Must Support nur Kard: Begründung Kardinalität beides: Begründung Kardinalität und Must Support

Habe betroffene Stellen geändert. In einzelnen Fällen ist nur die Kardinalität begründet. Das reicht mMn dort aber auch (z.B: wenn eine Min. Kard. gesetzt und begründet wird).

2024-10-17 17:44 UTC, alexzautke requested changes

2024-10-17 17:44 UTC, alexzautke commented on Resources/fsh-generated/resources/StructureDefinition-ISiKKalender.json
> +        "comment": "Begründung Kardinalität Must-Support-Flag (MS): Die Kardinalität 1..* und das Must-Support-Flag (MS) für das 'serviceType'-Element stellen sicher, dass jeder Kalender mindestens e
Und es gibt an welche "buchbaren Leistungen" überhaupt verfügbar sind.

2024-10-17 17:44 UTC, alexzautke commented on Resources/fsh-generated/resources/StructureDefinition-ISiKKalender.json
> -        "comment": "Hinweis: Für alle Target-Ressourcen SOLL ein Displaywert für die Referenz angegeben werden, sodass Systeme eine Übersicht der am Termin beteiligten Akteure anzeigen können ohne di
... sodass ein Termin-Consumer direkt anzeigen kann für welche Akteure ein Terminkalender existiert.

2024-10-17 17:44 UTC, alexzautke commented on Resources/fsh-generated/resources/StructureDefinition-ISiKKalender.json
> +        "comment": "Begründung Kardinalität und Must-Support-Flag (MS): Die Kardinalität der identifier-Eigenschaft wird auf 0..1 festgelegt, um sicherzustellen, dass optional ein Identifier vorhande
Finde ich tatsächlich im Nachhinein überflüssig

2024-10-17 17:44 UTC, alexzautke commented on Resources/fsh-generated/resources/StructureDefinition-ISiKTermin.json
> +        "comment": "Begründung zu Kardinalität und Must Support: Die Dienstleistungsart eines Termins ist von entscheidender Bedeutung, um die Verfügbarkeit und Planung des Termins zu gewährleisten.
Und auch um die Dauer des Termins in Abhängigkeit von der Dienstleistung zu ermitteln

2024-10-17 17:44 UTC, alexzautke commented on Resources/fsh-generated/resources/StructureDefinition-ISiKTermin.json
> +        "comment": "Hinweis: Zur Referenzierung auf eine Slot-Ressource MUSS eine Reference.reference mit einer URL verwendet werden. Das Termin-Repository muss so gestaltet sein, dass es aus Perspek
Reference.identifier wäre vor allem nicht geeignet um die Verknüpfung zu einem Kalender zu gewährleisten. Dies wäre insbesondere für das Termin-Repository relevant, da Termin zu speichern ohne zu wissen zu welchem Kalender diese gehören nicht optional wäre.

2024-10-23 13:09 UTC, f-peverali commented
TODO: hier ist zu prüfen, ob hier redundant Kardinalitäten im .fsh code angegeben wurde (obwohl diese mit Core Spec / ggf. abgeleitetem Profil übereinstimmen)

2024-10-28 09:47 UTC, alexzautke approved these changes

2024-10-28 13:03 UTC, f-peverali commented on Resources/input/fsh/ISiKKalender.fsh
>  * active 1..1 MS
```suggestion
* active 1.. MS
```

2024-10-28 13:05 UTC, f-peverali commented on Resources/input/fsh/ISiKKalender.fsh
> +  * ^comment = "Begründung Kardinalität und Must-Support-Flag (MS): Die Kardinalität 1..1 und das Must-Support-Flag (MS) für das 'active'-Element stellen sicher, dass jeder Kalender eindeutig als akt
```suggestion
  * ^comment = "Begründung Kardinalität und Must-Support-Flag (MS): Die Kardinalität 1..1 und das Must-Support-Flag (MS) für das 'active'-Element stellen sicher, dass jeder Kalender eindeutig als aktiv oder inaktiv gekennzeichnet ist. Dies ist entscheidend für die Ressourcenplanung und Verfügbarkeit von Terminen."
```

2024-10-28 13:19 UTC, f-peverali commented on Resources/input/fsh/ISiKKalender.fsh
> +  * ^comment = "Hinweis: Ein Kalender kann für einen Akteur gepflegt werden. Dieser Akteur kann in einer oder mehreren Fachrichtungen agieren. Für die Ressourcenplanung (z.B. welche Akteure sind für
```suggestion
  * ^comment = "Hinweis: Ein Kalender kann für ein Akteur gepflegt werden. Dieser Akteur kann in einer oder mehreren Fachrichtungen agieren. Für die Ressourcenplanung (z.B. welche Akteure sind für einen Termin verfügbar) sollte auch auf die Speciality des Akteurs zurückgegriffen werden für den Fall, dass ein Kalender pro Fachbereich, d.h. Akteur-übergreifend gepflegt wird. 
```

2024-10-28 13:24 UTC, f-peverali commented on Resources/input/fsh/ISiKKalender.fsh
> +    * ^comment = "Begründung Kardinalität und Must-Support-Flag (MS): Die Kardinalität der identifier-Eigenschaft wird auf 0..1 festgelegt, um sicherzustellen, dass optional ein Identifier vorhanden
```suggestion
    * ^comment = "Begründung Must-Support-Flag (MS):
```

2024-10-28 13:26 UTC, f-peverali commented on Resources/input/fsh/ISiKKalender.fsh
>    * display 0..1 MS
```suggestion
  * display MS
```

2024-10-28 13:26 UTC, f-peverali commented on Resources/input/fsh/ISiKKalender.fsh
> +    Begründung Kardinalität: Die Kardinalität der display-Eigenschaft wird auf 0..1 festgelegt, um sicherzustellen, dass ein Displaywert eindeutig ist, falls dieser vorhanden ist."
```suggestion
"  
```

2024-10-28 13:29 UTC, f-peverali commented on Resources/input/fsh/ISiKKalender.fsh
>    * identifier 0..1 MS
```suggestion
  * identifier MS
```

2024-10-28 13:35 UTC, f-peverali commented on Resources/input/fsh/ISiKNachricht.fsh
> +    * ^comment = "Begründung Kardinalität und Must-Support-Flag (MS): Die Kardinalität der identifier-Eigenschaft wird auf 0..1 festgelegt, um sicherzustellen, dass optional ein Identifier vorhanden
```suggestion
    * ^comment = "Begründung Kardinalität und Must-Support-Flag (MS): Die Kardinalität der identifier-Eigenschaft wird auf 0..1 festgelegt, um sicherzustellen, dass höchstens ein Identifier vorhanden ist."
```

2024-10-28 13:39 UTC, f-peverali commented on Resources/input/fsh/ISiKNachricht.fsh
> +    * ^comment = "Begründung Kardinalität und Must-Support-Flag (MS): Die Kardinalität der identifier-Eigenschaft wird auf 0..1 festgelegt, um sicherzustellen, dass optional ein Identifier vorhanden
```suggestion
    * ^comment = "Begründung Kardinalität und Must-Support-Flag (MS): Die Kardinalität der identifier-Eigenschaft wird auf 0..1 festgelegt, um sicherzustellen, dass höchstens ein Identifier vorhanden ist, damit ein Sender eindeutig über einen Identifier referenzierbar ist."
```

2024-10-28 13:39 UTC, f-peverali commented on Resources/input/fsh/ISiKTermin.fsh
> +  * ^comment = "Conditional Must Support - Einschränkung der übergreifenden MS-Definition: Falls ein bestätigungsrelevantes System das ISiK-Profil ISiKNachricht implementiert, MUSS das System auch di
```suggestion
  * ^comment = "Einschränkung der übergreifenden MS-Definition: Falls ein bestätigungsrelevantes System das ISiK-Profil ISiKNachricht implementiert, MUSS das System auch dieses Element unterstützten. Andernfalls KANN das System dieses Element unterstützen. Begründung zum Must Support: Nachrichten die für diesen Termin verfasst wurden können somit direkt abgerufen werden."
```

2024-10-28 13:42 UTC, f-peverali commented on Resources/input/fsh/ISiKTermin.fsh
>  * status 1..1 MS
```suggestion
* status MS
```

2024-10-28 13:43 UTC, f-peverali commented on Resources/input/fsh/ISiKTermin.fsh
> +  * ^comment = "Begründung zu Kardinalität und Must Support : Im ISiK Kontext ist der Status eines Termins von entscheidender Bedeutung, um den aktuellen Stand und die Verfügbarkeit des Termins zu ko
```suggestion
  * ^comment = "Begründung zu Must Support : Im ISiK Kontext ist der Status eines Termins von entscheidender Bedeutung, um den aktuellen Stand und die Verfügbarkeit des Termins zu kommunizieren."
```

2024-10-28 13:43 UTC, f-peverali commented on Resources/input/fsh/ISiKTermin.fsh
>  * cancelationReason 0..1 MS
```suggestion
* cancelationReason MS
```

2024-10-28 13:44 UTC, f-peverali commented on Resources/input/fsh/ISiKTermin.fsh
> +  * ^comment = "Begründung zu Kardinalität und Must Support: Dieses Feld ist optional (0..1), muss jedoch implemtiert werden (MS), um die Möglichkeit zu bieten, einen Grund für die Absage eines Termi
```suggestion
  * ^comment = "Begründung zu Must Support: Dieses Feld ist optional (0..1), muss jedoch implementiert werden (MS), um die Möglichkeit zu bieten, einen Grund für die Absage eines Termins zu hinterlegen."
```

2024-10-28 13:45 UTC, f-peverali commented on Resources/input/fsh/ISiKTermin.fsh
>  * slot 0..* MS
```suggestion
* slot MS
```

2024-10-28 13:47 UTC, f-peverali commented on Resources/input/fsh/ISiKTermin.fsh
> +* slot ^comment = "Begründung zu Kardinalität und Must Support: Die Kardinalität der slot-Eigenschaft wird auf 0..* festgelegt, sodass ein Termin-Requestor bei der Terminbuchung nur einen Termin und
```suggestion
* slot ^comment = "Begründung zu Kardinalität und Must Support: Die Kardinalität der slot-Eigenschaft bleibt 0..*, sodass ein Termin-Requestor bei der Terminbuchung nur einen Termin und ein Verweis auf ein ISiKKalender übergeben kann. Es ist dann die Aufgabe des Termin-Repositories in Abhängigkeit der gebuchten Dienstleistung freie Terminblöcke zu finden. Diese sind im Appointment zu referenzieren."
```

2024-10-28 13:48 UTC, f-peverali commented on Resources/input/fsh/ISiKTermin.fsh
>  * participant 1..* MS
```suggestion
* participant MS
```

2024-10-28 13:48 UTC, f-peverali commented on Resources/input/fsh/ISiKTermin.fsh
> +Begründung zu Kardinalität und Must Support: Die Teilnehmer eines Termins sind von entscheidender Bedeutung, um die Verfügbarkeit und Planung des Termins zu gewährleisten. Daher ist dieses Feld verpf
```suggestion
Begründung zu Kardinalität und Must Support: Die Teilnehmer eines Termins sind von entscheidender Bedeutung, um die Verfügbarkeit und Planung des Termins zu gewährleisten. Daher muss dieses Feld unterstützt werden (MS)."
```

2024-10-28 13:49 UTC, f-peverali commented on Resources/input/fsh/ISiKTermin.fsh
>  * specialty 0..* MS
```suggestion
* specialty MS
```

2024-10-28 13:51 UTC, f-peverali commented on Resources/input/fsh/ISiKTermin.fsh
> +  * ^comment = "Begründung zu Kardinalität und Must Support: Die Priorität eines Termins ist von entscheidender Bedeutung, um die Dringlichkeit und Relevanz des Termins zu kommunizieren und zu priori
```suggestion
  * ^comment = "Begründung zu Kardinalität und Must Support: Die Priorität eines Termins ist von entscheidender Bedeutung, um die Dringlichkeit und Relevanz des Termins zu kommunizieren und zu priorisieren. Eine Priorität ist nicht zwingend erforderlich, muss jedoch implementiert werden (MS), um die Möglichkeit zu bieten, die Dringlichkeit und Relevanz des Termins abzurufen."
```

2024-10-28 13:54 UTC, f-peverali commented on Resources/input/fsh/ISiKTerminblock.fsh
> +* schedule ^comment = "Begründung Kardinalität: Die Kardinalität der schedule-Eigenschaft wird auf 1..1 festgelegt, um sicherzustellen, dass ein Terminblock immer auf genau einen Kalender verweist. A
```suggestion
* schedule ^comment = "Begründung Kardinalität und MS: Die Kardinalität der reference-Eigenschaft wird auf 1..* festgelegt, um sicherzustellen, dass ein Kalender eindeutig referenziert und identifiziert werden kann."
```

2024-10-28 13:54 UTC, f-peverali commented on Resources/input/fsh/ISiKTerminblock.fsh
>  * schedule 1..1 MS
```suggestion
* schedule MS
```

2024-10-28 13:55 UTC, f-peverali commented on Resources/input/fsh/ISiKTerminblock.fsh
>  * status 1..1 MS
```suggestion
* status MS
```

2024-10-28 13:56 UTC, f-peverali commented on Resources/input/fsh/ISiKTerminblock.fsh
> +* status ^comment = "Begründung Kardinalität: Die Kardinalität der status-Eigenschaft wird auf 1..1 festgelegt, um sicherzustellen, dass der Status eines Terminblocks immer angegeben wird. Dies ist w
```suggestion
* status ^comment = "Begründung Must Support: Dies ist wichtig, um die Verfügbarkeit von Terminen zu gewährleisten, eine Überbuchung zu verhindern und zudem einem Termin-Requestor die Möglichkeit zu bieten nur freie Termine bei der Terminbuchung anzuzeigen."
```

2024-10-28 13:56 UTC, f-peverali commented on Resources/input/fsh/ISiKTerminblock.fsh
>  * start 1..1 MS
```suggestion
* start MS
```

2024-10-28 13:57 UTC, f-peverali commented on Resources/input/fsh/ISiKTerminblock.fsh
> +* start ^comment = "Begründung Kardinalität: Die Kardinalität der start-Eigenschaft wird auf 1..1 festgelegt, um sicherzustellen, dass der Startzeitpunkt eines Terminsblocks immer angegeben wird. Die
```suggestion
* start ^comment = "Begründung Must Support: Dies ist wichtig, um den Zeitpunkt des Termins an einen Termin-Requestor / Termin-Consumer zu kommunizieren."
```

2024-10-28 13:57 UTC, f-peverali commented on Resources/input/fsh/ISiKTerminblock.fsh
>  * end 1..1 MS
```suggestion
* end MS
```

2024-10-28 13:57 UTC, f-peverali commented on Resources/input/fsh/ISiKTerminblock.fsh
> +* end ^comment = "Begründung Kardinalität: Die Kardinalität der end-Eigenschaft wird auf 1..1 festgelegt, um sicherzustellen, dass der Endzeitpunkt eines Terminsblocks immer angegeben wird. Dies ist
```suggestion
* end ^comment = "Begründung Must Support: Dies ist wichtig, um die Länge des Termins an einen Termin-Requestor / Termin-Consumer zu kommunizieren."
```

2024-10-28 14:11 UTC, merged