refactoring CapabilityStatement
gematik/ISiK-Terminplanung pull request #212
Opened 2024-09-27 14:48 UTC by simoneOnFhir

Bin mit dem Refactoring des CapabilityStatements durch. Bitte Issue #210  und #211 beachten!

Überall dort, wo noch die Motivationen für die erforderlichen Interaktionen fehlen, habe ich jeweils eine FSH-Zeile der Form 
`* documentation = "ToDo" `
hinzugefügt.

2024-10-01 08:01 UTC, f-peverali commented
question: @simoneOnFhir hast du das Rendering dafür geprüft?

2024-10-01 10:12 UTC, simoneOnFhir commented
nope. dafür bräuchten wir entweder eine weitere Sandbox oder müssten den Simplifier-Hook auf den TC branch umstellen, den alten IG migrieren und einen TC IG anlegen...

2024-10-17 17:50 UTC, alexzautke requested changes

2024-10-17 17:50 UTC, alexzautke commented on Resources/input/fsh/ISiKTerminplanungCapabilityStatement.fsh
> +    * searchInclude[+] = "Communication:recipient"
Diese includes sollten herausgenommen werden, da die Communication-Ressource nun komplett optional ist.

2024-11-08 13:03 UTC, f-peverali requested changes
issue: hier fehlt die post Anforderung , wie beschrieben in https://simplifier.net/guide/isik-terminplanung-v4/ImplementationGuide-markdown-Datenobjekte-Operations?version=current

"Ein Termin Repository MUSS die Anlage (Create-Interaktion) einer Patient-Ressource entsprechend der Vorgaben des [ISiK-Basismoduls](https://simplifier.net/guide/isik-basis-v4/markdown-UebergreifendeFestlegungen-UebergreifendeFestlegungen_Rest?version=current) unterstützen."

2024-11-26 20:30 UTC, alexzautke approved these changes

2024-11-27 08:23 UTC, merged