Reference to basis module main
gematik/ISiK-Terminplanung pull request #221
Opened 2024-10-22 12:05 UTC by leslieber

Please go the the `Preview` tab and select the appropriate sub-template:

[**Contributor PR**](?expand=1&template=PR_Template_Contributor.md)

[Version Upgrade **(for Admins)**](?expand=1&template=PR_Template_VersionUpgrade.md)

## Pull Request Short Cut

2024-10-22 13:47 UTC, f-peverali reviewed
todo: ggf. sollte die main.yml überschireben werden

suggestion: dienen PR erstmal als "Draft" kennzeichnen (über die github UI)

praise: well done!

2024-11-11 10:05 UTC, f-peverali requested changes

2024-11-11 10:05 UTC, f-peverali commented on .github/workflows/main.yml
> +      - main-stufe-4
issue: so wir die action nur im falle von Änderungen am definierten branch getriggert. Wir wollen aber mehr Fälle.

suggestion: hier am besten nach dem Schema von Basis die Bedingungen für die Ausführung setzen

2024-11-14 14:06 UTC, leslieber commented on .github/workflows/main.yml
> +      - main-stufe-4
Das könnte ja eigentlich so bleiben, wie es war, oder?

2024-11-14 14:35 UTC, f-peverali commented on .github/workflows/main.yml
> +      - main-stufe-4
genau

2024-11-20 12:26 UTC, f-peverali submitted a review, later dismissed

2024-12-04 15:40 UTC, f-peverali submitted a review, later dismissed

2024-12-05 13:57 UTC, f-peverali approved these changes

2024-12-05 13:59 UTC, f-peverali approved these changes

2024-12-05 13:59 UTC, merged