Klarstellung, dass Freitextbeschreibung der Dienstleistung ausreichend ist - Stufe 2
gematik/ISiK-Terminplanung pull request #229
Opened 2024-10-25 13:47 UTC by alexzautke

Fixes PTDATA-1093 - Stufe 2

2024-10-28 07:36 UTC, f-peverali requested changes
comment: in dieser stufe würde ich kein MS mehr ad hoc einführen

2024-10-28 07:38 UTC, alexzautke commented
@f-peverali Das MS-Flag ist Stand heute bereits auf dem Element. Mit der aktuellen Spec ist es unklar welche Subelemente unterstützt werden müssen. Wir würden effektiv hier MS-Flags wegnehmen (auf dem Coding).

2024-10-28 07:48 UTC, f-peverali reviewed
suggestion: ggf. statt MS Hinweis hinzu, dass das Feld .serviceType.text genutzt werden soll

2024-10-28 07:53 UTC, f-peverali commented
> @f-peverali Das MS-Flag ist Stand heute bereits auf dem Element. Mit der aktuellen Spec ist es unklar welche Subelemente unterstützt werden müssen. Wir würden effektiv hier MS-Flags wegnehmen (auf dem Coding).
question: war es nicht das Ziel hier den Constraint für Coding zu entfernen?

2024-11-08 13:41 UTC, f-peverali approved these changes

2024-11-08 13:42 UTC, merged