add MS + textual constraint #72
gematik/ISiK-Terminplanung pull request #91
Opened 2023-05-19 13:09 UTC by f-peverali

Dieser Pull Request soll eine Lösung zur Änderung der Appointment.specialty mit gelockerter Kardinalität bereitstellen, die dennoch durch textuelle Festlegung ein Verarbeiten/Rendering in geforderten Szenarien (Terminbuchung über Patientenportal) sicherstellt - wie in AG-Sitzung am 5.5. beschlossen.

2023-05-25 07:42 UTC, jcaumann commented on ImplementationGuide/markdown/Datenobjekte/ISiKTerminAppointment.md
> +**Hinweis:** Falls eine Kodierung der Fachrichtung für den Termin angegeben werden kann, dann MUSS sie angegeben werden und exponiert werden können (eine Ausnahme bildet hier die fachrichtungs-unabhä
Alternative als Vorschlag:
**Hinweis:** Sofern aus den auf der Appointment-Ressource aufsetzenden Anwendungsfällen eine weitere Verarbeitung der Ressource durch einen menschlichen Nutzer nicht ausgeschlossen werden kann, MUSS das bestätigungsrelevante System mit dem Termin verbundenen Ressourcen (insb. Appointment.slot, Appointment.slot.schedule, Appointment.participant:AkteurMedizinischeBehandlungseinheit.actor) oder aus dem spezifischen Kontext verfügbare Informationen auswerten, um das Element `Appointment.speciality` mit einem sinnvollen Wert zu befüllen.

2023-05-25 07:42 UTC, jcaumann requested changes
siehe alterativen Vorschlag (Kommentar)

2023-05-26 12:30 UTC, f-peverali commented on ImplementationGuide/markdown/Datenobjekte/ISiKTerminAppointment.md
> +**Hinweis:** Falls eine Kodierung der Fachrichtung für den Termin angegeben werden kann, dann MUSS sie angegeben werden und exponiert werden können (eine Ausnahme bildet hier die fachrichtungs-unabhä
Verbesserung für den "Hinweis": Sofern aus den auf der Appointment-Ressource aufsetzenden Anwendungsfällen eine weitere Verarbeitung der Ressource durch einen menschlichen Nutzer nicht ausgeschlossen werden kann, MUSS das bestätigungsrelevante System mit dem Termin verbundenen Ressourcen (insb. `Appointment.slot`, `Appointment.slot.schedule`, `Appointment.participant:AkteurMedizinischeBehandlungseinheit.actor`) oder aus dem spezifischen Kontext verfügbare Informationen auswerten und das Element `Appointment.speciality` mit einem sinnvollen Wert kodieren (eine Ausnahme bildet hier zum Beispiel die fachrichtungs-unabhängige Terminplanung durch krankenhausinterne, zentrale Organisationseinheiten).

2023-05-26 13:02 UTC, f-peverali commented on ImplementationGuide/markdown/Datenobjekte/ISiKTerminAppointment.md
> +**Hinweis:** Falls eine Kodierung der Fachrichtung für den Termin angegeben werden kann, dann MUSS sie angegeben werden und exponiert werden können (eine Ausnahme bildet hier die fachrichtungs-unabhä
wie oben umgesetzt

2023-05-26 13:03 UTC, merged