Fix/actor cardinality
gematik/ISiK-Terminplanung pull request #95
Opened 2023-05-23 09:23 UTC by f-peverali

2023-05-28 10:42 UTC, alexzautke commented
Auf welches Issue bezieht sich hier die Änderung? Ich verstehe den PR nicht ganz 😅

2023-05-30 06:23 UTC, f-peverali commented
> Auf welches Issue bezieht sich hier die Änderung? Ich verstehe den PR nicht ganz 😅

https://github.com/gematik/spec-ISiK-Terminplanung/issues/86 hier ging es um das Rendering in simplifier. Bin mir aber unsicher, ob es nicht an unserer Pipeline liegt (sushi slicings). ICh denke da sollten wir in einer TC für alle Stufen umsetzen.

2023-05-30 06:40 UTC, alexzautke commented
Ich frag mal beim Simplifier-Team nach, wieso das Rendering hier keinen “All Slices”-Slice anzeigt.

2023-05-30 06:43 UTC, alexzautke requested changes

2023-05-30 06:43 UTC, alexzautke commented on Resources/input/fsh/ISiKTermin.fsh
> +* participant[AkteurPatient].actor 1..1 MS
Die Kardinalität von .Status solle auch in den Slices angepasst werden

2023-10-12 21:55 UTC, alexzautke commented
@f-peverali Hab meinen Review-Kommentar selbst behoben. Die Änderung kann gerne mit der nächsten TC publiziert werden.

2023-10-23 13:07 UTC, closed without merging